_wandb:
    value:
        cli_version: 0.24.2
        e:
            9y0rjv3d1yj5dlcv2hnisan935xv7bcc:
                args:
                    - --model_name=Densenet
                    - --model_layer=169
                    - --optimizer=ADAM
                    - --lrs=False
                    - --image_type=RGB
                    - --cuda_index=0
                    - --train_mode=True
                    - --test_object=False
                    - --mixed_image=True
                    - --pretrained=False
                    - --batch_size=64
                    - --num_epoch=200
                    - --learning_rate=5.0e-4
                    - --weight_decay=0.0
                    - --num_workers=8
                codePath: force_estimation/train.py
                codePathLocal: train.py
                cpu_count: 96
                cpu_count_logical: 192
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "32212254720"
                        used: "17070346240"
                email: creativelf@outlook.com
                executable: /root/miniconda3/envs/9dtact/bin/python
                git:
                    commit: 2dabe36bbe325575ea825dcf7dba0f3e55d22469
                    remote: https://github.com/Hcreativelf/9DTact.git
                gpu: NVIDIA GeForce RTX 4090 D
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 14592
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090 D
                      uuid: GPU-915cf297-889b-ff8c-04f7-5ac0d2908d3f
                host: autodl-container-4e0e468bcd-00b8bc54
                memory:
                    total: "1081834651648"
                os: Linux-5.15.0-94-generic-x86_64-with-glibc2.17
                program: train.py
                python: CPython 3.8.20
                root: /root/autodl-tmp/9DTact/force_estimation
                startedAt: "2026-03-09T11:24:03.580072Z"
                writerId: 9y0rjv3d1yj5dlcv2hnisan935xv7bcc
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.8.20
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
batch_size:
    value: 64
end_factor:
    value: 0.4
image_type:
    value: RGB
learning_rate:
    value: 0.0005
lrs:
    value: false
mixed_image:
    value: true
model_type:
    value: Densenet-169
num_epoch:
    value: 200
optimizer:
    value: ADAM
pretrained:
    value: false
test_object:
    value: false
total_iters:
    value: 20
weight_decay:
    value: 0
